version: '{build}-{branch}'

branches:
  # whitelist
  only:
    - master

clone_depth: 50


init:
- ps: |
    function craft() {
        & C:\python36\python.exe "$env:APPVEYOR_BUILD_FOLDER\$env:TARGET\craft\bin\craft.py" $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --branch v0.2.2 --depth=1 git://anongit.kde.org/craftmaster.git $env:APPVEYOR_BUILD_FOLDER\CraftMaster 2>&1"
    & C:\python36\python.exe $env:APPVEYOR_BUILD_FOLDER\CraftMaster\CraftMaster.py --config $env:APPVEYOR_BUILD_FOLDER\appveyor.ini --target $env:TARGET
    craft -p gammaray
    craft nsis
    craft --install-deps gammaray

build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER gammaray

after_build:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER --package gammaray


#test_script:
#- ps: |
   #craft --src-dir $env:APPVEYOR_BUILD_FOLDER --test gammaray
test: off

environment:
    matrix:
    - TARGET: msvc2015x86
    #- TARGET: mingw
    #- TARGET: msvc2015x64

artifacts:
  - path: binaries/*

deploy:
    - provider: Environment
      name: kdab
      artifact:
      #on:
       #   branch: master
